version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  vector:
    image: ankane/pgvector
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'
  api:
    build: ../api
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/saasdb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      WEBPAY_API_KEY: ${WEBPAY_API_KEY}
    ports:
      - '4000:4000'
    depends_on:
      - db
      - vector
  web:
    build: ../web
    environment:
      API_URL: http://api:4000
    ports:
      - '3000:3000'
    depends_on:
      - api
  n8n:
    image: n8nio/n8n
    environment:
      N8N_PORT: ${N8N_PORT}
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
volumes:
  db_data:
  n8n_data:
